framework:
    workflows:
        ton_macron_invitation:
            type: state_machine
            supports: [AppBundle\TonMacron\InvitationProcessor]
            places:
                - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INFO
                - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_SUMMARY
                - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_SENT
            transitions:
                !php/const:AppBundle\TonMacron\InvitationProcessor::TRANSITION_FILL_INFO:
                    from:
                        - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INFO
                    to: !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                !php/const:AppBundle\TonMacron\InvitationProcessor::TRANSITION_FILL_PROJECT:
                    from:
                        - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                    to: !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                !php/const:AppBundle\TonMacron\InvitationProcessor::TRANSITION_FILL_INTERESTS:
                    from:
                        - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                    to: !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                !php/const:AppBundle\TonMacron\InvitationProcessor::TRANSITION_FILL_REASONS:
                    from:
                        - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                    to: !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_SUMMARY
                !php/const:AppBundle\TonMacron\InvitationProcessor::TRANSITION_SEND:
                    from:
                        - !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_SUMMARY
                    to: !php/const:AppBundle\TonMacron\InvitationProcessor::STATE_SENT
